name: 'fridge_watcher'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  dart_config: 0.5.0
  browser: any
  polymer: ">=0.16.0 <0.17.0"
  core_elements: '^0.6.1'
  paper_elements: '^0.6.2'
  di: any
  http: any
  uri: ">=0.9.3 <0.10.0"
  query_string: any
  route: any
  intl: any
  event_bus: any
  redstone_mapper: '0.2.0-beta.1'
  fridge_watcher_shared:
    path: ../shared
dev_dependencies:
  test: 0.12.2
dependency_overrides:
  redstone_mapper:
    git:
      url: git://github.com/Pacane/redstone_mapper.git
      ref: update-analyzer-dependency
transformers:
- polymer:
    entry_points:
    - web/index.html
- redstone_mapper
- di