name: 'fridge_watcher'
version: 0.0.1
description: >
  An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  polymer: ">=0.16.0 <0.17.0"
  core_elements: '^0.6.1'
  paper_elements: '^0.6.2'
  di: any
#  firebase: ">=0.5.0 <0.6.0"
#  meta: ">=0.8.8 <0.9.0"
#  http_server: any
  http: any
  uri: ">=0.9.3 <0.10.0"
  query_string: any
  route: any
  intl: any
#  html5lib: ">=0.12.0 <0.13.0"
#  notification: ">=0.0.1 <0.1.0"
  event_bus: any
dev_dependencies:
  shelf: any
  shelf_static: any
transformers:
- polymer:
    entry_points:
    - web/index.html